"""Background patterns — Vidlore's 10-preset "Choose background image" grid.

Each background is a small procedural PIL generator (no external asset
download, no heavy bundling). They are used as the BASE LAYER for:
  • slide fallbacks (when no real footage is matched) — replaces the
    plain theme gradient
  • document / explainer / number card backgrounds
  • intro card / chapter card backdrops

The renderer asks for a background by name; if the user picked "auto"
(or an unknown name) the theme's own gradient is used so nothing breaks.
Thumbnails for the web picker are generated by `thumbnail(name, ...)`
and cached on disk so the picker stays snappy.
"""
from __future__ import annotations

import math
import random
from pathlib import Path
from typing import Callable

from PIL import Image, ImageDraw, ImageFilter

# Stable picker order — what the UI grid renders in. The first entry is
# the implicit default the form ships with selected.
BG_NAMES: list[str] = [
    "modern_lines",
    "gradient_gray",
    "green_gradient",
    "blue_minimal",
    "paper_texture",
    "grid_pattern",
    "pure_black",
    "red_grid",
    "vintage",
    "red_glow",
]

# Human-readable label per background (shown under the thumbnail).
BG_TITLES: dict[str, str] = {
    "modern_lines":   "Modern Lines",
    "gradient_gray":  "Gradient Gray",
    "green_gradient": "Green Gradient",
    "blue_minimal":   "Blue Minimal",
    "paper_texture":  "Paper Texture",
    "grid_pattern":   "Grid Pattern",
    "pure_black":     "Pure Black",
    "red_grid":       "Red Grid",
    "vintage":        "Vintage",
    "red_glow":       "Red Glow",
}


# ----- helpers ---------------------------------------------------------------

def _lerp(a: tuple, b: tuple, t: float) -> tuple:
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))


def _gradient(size, c1, c2, *, direction: str = "v") -> Image.Image:
    """Smooth linear gradient base. direction: 'v' top→bot, 'h' left→right,
    'd' top-left→bot-right (diagonal)."""
    w, h = size
    img = Image.new("RGB", size, c1)
    px = img.load()
    if direction == "h":
        for x in range(w):
            col = _lerp(c1, c2, x / max(1, w - 1))
            for y in range(h):
                px[x, y] = col
    elif direction == "d":
        m = max(1, w + h - 2)
        for y in range(h):
            for x in range(w):
                px[x, y] = _lerp(c1, c2, (x + y) / m)
    else:  # vertical
        for y in range(h):
            col = _lerp(c1, c2, y / max(1, h - 1))
            for x in range(w):
                px[x, y] = col
    return img


def _vignette(img: Image.Image, strength: float = 0.55) -> None:
    """Darken corners in place to focus the eye on the center."""
    w, h = img.size
    overlay = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    d = ImageDraw.Draw(overlay)
    cx, cy = w / 2, h / 2
    rmax = math.hypot(cx, cy)
    step = max(2, h // 60)
    for i in range(0, int(rmax), step):
        a = int(min(255, strength * 255 * (i / rmax) ** 2.2))
        d.ellipse([cx - rmax + i, cy - rmax + i,
                   cx + rmax - i, cy + rmax - i],
                  outline=(0, 0, 0, a))
    img.paste(overlay, (0, 0), overlay)


def _noise(img: Image.Image, amount: int = 8, seed: int = 1) -> None:
    """Sprinkle subtle film-like noise on top (in place)."""
    rnd = random.Random(seed)
    w, h = img.size
    px = img.load()
    for _ in range(int(w * h * 0.04)):
        x = rnd.randrange(w); y = rnd.randrange(h)
        r, g, b = px[x, y]
        d = rnd.randint(-amount, amount)
        px[x, y] = (max(0, min(255, r + d)),
                    max(0, min(255, g + d)),
                    max(0, min(255, b + d)))


# ----- 10 backgrounds --------------------------------------------------------

def _bg_modern_lines(size, accent) -> Image.Image:
    """Deep navy with very subtle horizontal lines — a clean tech base."""
    img = _gradient(size, (12, 16, 26), (22, 28, 44), direction="v")
    d = ImageDraw.Draw(img, "RGBA")
    w, h = size
    for y in range(0, h, 14):
        d.line([(0, y), (w, y)], fill=(255, 255, 255, 8))
    return img


def _bg_gradient_gray(size, accent) -> Image.Image:
    img = _gradient(size, (38, 40, 44), (78, 82, 90), direction="v")
    _vignette(img, 0.25)
    return img


def _bg_green_gradient(size, accent) -> Image.Image:
    img = _gradient(size, (12, 60, 44), (32, 130, 90), direction="d")
    _vignette(img, 0.30)
    return img


def _bg_blue_minimal(size, accent) -> Image.Image:
    img = _gradient(size, (200, 220, 232), (220, 232, 240), direction="v")
    return img


def _bg_paper_texture(size, accent) -> Image.Image:
    """Cream paper with horizontal grain + noise."""
    img = Image.new("RGB", size, (240, 232, 214))
    d = ImageDraw.Draw(img, "RGBA")
    w, h = size
    rnd = random.Random(7)
    for y in range(0, h, 3):
        a = rnd.randint(4, 12)
        d.line([(0, y), (w, y)], fill=(160, 130, 90, a))
    _noise(img, 6, seed=21)
    _vignette(img, 0.18)
    return img


def _bg_grid_pattern(size, accent) -> Image.Image:
    """Dark with thin gray grid — the most 'tech editor' option."""
    img = Image.new("RGB", size, (12, 16, 22))
    d = ImageDraw.Draw(img, "RGBA")
    w, h = size
    step = max(28, h // 30)
    for x in range(0, w, step):
        d.line([(x, 0), (x, h)], fill=(255, 255, 255, 14))
    for y in range(0, h, step):
        d.line([(0, y), (w, y)], fill=(255, 255, 255, 14))
    _vignette(img, 0.35)
    return img


def _bg_pure_black(size, accent) -> Image.Image:
    img = Image.new("RGB", size, (4, 4, 6))
    _vignette(img, 0.20)
    return img


def _bg_red_grid(size, accent) -> Image.Image:
    """Deep red with darker grid — looks like a classified overlay."""
    img = Image.new("RGB", size, (120, 24, 24))
    d = ImageDraw.Draw(img, "RGBA")
    w, h = size
    step = max(28, h // 30)
    for x in range(0, w, step):
        d.line([(x, 0), (x, h)], fill=(0, 0, 0, 50))
    for y in range(0, h, step):
        d.line([(0, y), (w, y)], fill=(0, 0, 0, 50))
    _vignette(img, 0.45)
    return img


def _bg_vintage(size, accent) -> Image.Image:
    """Aged sepia paper with spots."""
    img = _gradient(size, (230, 214, 180), (200, 178, 140), direction="d")
    d = ImageDraw.Draw(img, "RGBA")
    w, h = size
    rnd = random.Random(9)
    for _ in range(60):
        cx, cy = rnd.randrange(w), rnd.randrange(h)
        rr = rnd.randint(20, 90)
        a = rnd.randint(8, 24)
        d.ellipse([cx - rr, cy - rr, cx + rr, cy + rr],
                  fill=(110, 80, 40, a))
    img = img.filter(ImageFilter.GaussianBlur(2.2))
    _noise(img, 10, seed=31)
    _vignette(img, 0.40)
    return img


def _bg_red_glow(size, accent) -> Image.Image:
    """Black with a deep red radial glow in the center."""
    w, h = size
    img = Image.new("RGB", size, (4, 4, 6))
    d = ImageDraw.Draw(img, "RGBA")
    cx, cy = w / 2, h / 2
    rmax = math.hypot(cx, cy)
    step = max(2, h // 80)
    for i in range(0, int(rmax), step):
        t = 1.0 - (i / rmax)
        a = int(180 * (t ** 2.4))
        d.ellipse([cx - rmax + i, cy - rmax + i,
                   cx + rmax - i, cy + rmax - i],
                  outline=(150, 20, 20, a))
    img = img.filter(ImageFilter.GaussianBlur(28))
    return img


_BG_FUNCS: dict[str, Callable] = {
    "modern_lines":   _bg_modern_lines,
    "gradient_gray":  _bg_gradient_gray,
    "green_gradient": _bg_green_gradient,
    "blue_minimal":   _bg_blue_minimal,
    "paper_texture":  _bg_paper_texture,
    "grid_pattern":   _bg_grid_pattern,
    "pure_black":     _bg_pure_black,
    "red_grid":       _bg_red_grid,
    "vintage":        _bg_vintage,
    "red_glow":       _bg_red_glow,
}


def generate(
    name: str,
    size: tuple[int, int],
    accent: tuple[int, int, int] = (255, 255, 255),
) -> Image.Image | None:
    """Return a PIL image of the background. None if the name is 'auto' /
    unknown (caller should fall back to theme gradient)."""
    fn = _BG_FUNCS.get(name)
    if not fn:
        return None
    return fn(size, accent)


def thumbnail(
    name: str,
    size: tuple[int, int] = (260, 150),
    cache_dir: Path | None = None,
) -> Path | None:
    """Generate (and disk-cache) a small PNG thumbnail for the web picker.
    Returns the path on disk, or None if the name is unknown."""
    if name not in _BG_FUNCS:
        return None
    if cache_dir is None:
        cache_dir = Path.home() / ".vidlore" / "bg_thumbs"
    cache_dir.mkdir(parents=True, exist_ok=True)
    out = cache_dir / f"{name}_{size[0]}x{size[1]}.png"
    if out.exists():
        return out
    img = generate(name, size)
    if img is None:
        return None
    img.save(out, "PNG", optimize=True)
    return out


def bg_meta_list() -> list[dict]:
    """Lightweight subset for the web picker — name + title each."""
    return [{"name": n, "title": BG_TITLES[n]} for n in BG_NAMES]


def is_valid(name: str) -> bool:
    """True for any of the 10 names or the explicit 'auto' default."""
    return name == "auto" or name in _BG_FUNCS
